triggers:
- envs: []
  last_enabled_at: 2024-02-06 02:16:46.761491
  name: daily_5am_utc_run
  pipeline_uuid: green_taxi_etl
  schedule_interval: '@daily'
  schedule_type: time
  settings: null
  sla: null
  start_time: 2024-02-05 05:00:00
  status: active
  variables: {}
